### ISSUE TITLE
'AuditEntry' Entity needs to be added in the data model.

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal-3.0#11]
- Audit entry parameters need to be defined.
- =current session id= need to be changed to =current session user id=
- =updating-entry-id= need to be changed to =updated-entry-id=
- Audit entry should be only able to read the data.
- In AuditEntry, operations with parameters and its timestamp need to
  be captured so that AuditEntry should be used to reconstruct the
  database.

**Comment by iangfernandes96** [comment]
I changed the first three points, as requested, in the data-model.
However, for the last two points, after speaking with Thirumal, we agreed that they need to be done from an implementation standpoint, and hence, need not be highlighted in the data-model.
