### ISSUE TITLE
Formal Notations need to be followed in the data model

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal-3.0#12]
- Section 4: Relations and cardinality constraints over entity types
  change the first note description with the following equation:  
  if s1.user = s2.user -> s1.role != s2.role
- In Referrential Integraty,
  user-set
  admin-user-set = { u E user-set | admin E roles(u)} admin-user-set != null 
  In relations,
  role need to be changed to roles
- Effect:
  assume u = new User()
  1. roles(u) = {guest}
  2. user-set = user-set U {u}

**Comment by travula** [comment]
Review Comments incorporated
