### ISSUE TITLE
Requirements Review Meeting Notes on 28/06/2016

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal-3.0#13]
- Requirements should be changed to user requirements, role requirements, etc.

_Requirement 1_
1. User: User is an entity in the System (Add links to the formal spec)
2. Email: Email is an entity in the System

_Requirement 2_
1. Each user has an Email

_Formal Requirements Spec_
Entities:
User: ENTITY ---> referred to requirement1 (Add links to requirements)
Email: ENTITY ---> referred to requirement1 
email: User > Email! ---> referred to requirement2

**Comment by travula** [comment]
This is a duplicate of #2
