### ISSUE TITLE
Data Model of the application without events

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal-3.0#3]
Data Model for part1 of outreach portal-3.0 which includes the following entities. 
1) Name
2) Email
3) Role
4) User
5) Institute
6) OC
7) NC
8) Session
9) System

**Comment by madhavipuliraju** [comment]
Adding one more entity:
10) Audit

Please find the link: https://github.com/vlead/outreach-portal-3.0/blob/object-model/src/runtime/objects/entities.org

'Audit' Entity need to be implemented.

**Comment by priya100raman** [comment]
Link for the Data Model Part 1 : The documentation of data-model can be found at [https://github.com/vlead/outreach-portal-3.0/blob/data-model-events/src/data-model/index.org]
