### ISSUE TITLE
Object model of the entities described in part 1 of data-model

### ISSUE THREAD

**Issue by namrathadeepthi** [vlead/outreach-portal-3.0#4]
The following entities should be  implemented:
1) Name
2) Email
3) Role
4) User
5) Institute
6) OC
7) NC
8) Session

**Comment by madhavipuliraju** [comment]
Adding one more entity:
9) Audit 

Please find the link: https://github.com/vlead/outreach-portal-3.0/blob/object-model/src/runtime/objects/entities.org

'Audit' Entity need to be added.
