### ISSUE TITLE
Object model of System of outreach portal 3.0

### ISSUE THREAD

**Issue by namrathadeepthi** [vlead/outreach-portal-3.0#5]
Object model of System of outreach portal 3.0 which includes the following operations:
1) AddUser
2) AddRole
3) CreateOC
4) CreateNC
5) Login
6) Logout
7) DeleteUser
8)UpdateUser

**Comment by madhavipuliraju** [comment]
More Operations:
9) UpdateInstitute
10) CreateInstitute

**Comment by madhavipuliraju** [comment]
Above 10 operations and its test cases are done. 
Please find the link: https://github.com/vlead/outreach-portal-3.0/blob/object-model/src/runtime/system/system.org

**Comment by madhavipuliraju** [comment]
This object model does not include the new role NOC (National Outreach Coordinator) and Audit entity.
